### ISSUE TITLE
Compiling fails

### ISSUE THREAD

**Issue by illera88** [matthiaskramm/swftools#12]
Hi,
I'm in a Debian 64 bits and I'm failing to build swftools:

I do:
`git clone https://github.com/matthiaskramm/swftools`
`cd swftools`
`./configure`
`make`

Configure runs well but when the make I get:

```terminal
make[2]: Leaving directory '/tmp/swftools/lib/pdf'
Makefile:184: recipe for target 'libgfxpdf.a' failed
make[1]: Leaving directory '/tmp/swftools/lib'
Makefile:7: recipe for target 'all' failed
make[2]: *** No rule to make target 'xpdf/TextOutputDev.o', needed by '../libgfxpdf.a'.  Stop.
make[1]: *** [libgfxpdf.a] Error 2
make: *** [all] Error 2
```

Any idea why? 

Thanks

**Comment by matthiaskramm** [comment]
Could you try running "make" again, just to make sure this is not a transient failure?

**Comment by illera88** [comment]
You are right. It works if I run make again. Why is that?? I am creating a Dockerfie and I cand build the container image since the first make exits with error. 

Thanks for your fast response

**Comment by matthiaskramm** [comment]
As far as I'm aware, it's a bug in make. I can try to dig up the bug number if you're interested.

**Comment by illera88** [comment]
I did a little trick so Docker does not exit after the failure so this is not a priority for me. 

Thanks again!

**Comment by coderobe** [comment]
This is still happening. Do you have a bug reference to the `bug in make` you're.. referencing? I think this is much more likely to be a dependency issue in one of the autotools include files than a `make` bug.

**Comment by matthiaskramm** [comment]
Hm. I remember @alexeyv and me digging through the gmake bug list and finding one that described the exact scenario. But I can't find it anymore.

It's perfectly possible that you're right, and that this is just a bug in one of swftools' make files. But if so, it's a subtle bug.

`lib/pdf/Makefile` declares the programmatic rule:

```
xpdf/%.$(O): xpdf/%.cc
        $(CC) -I ./ -I xpdf $< -o $@           
```

And there *is* a `xpdf/TextOutputDev.cc`, so said rule should kick in. But make sometimes complains that it doesn't have a rule to build `xpdf/TextOutputDev.o`!

I think to debug this, we'd have to compile our own make, sprinkle `printf`s over it and see where it goes wrong.
