### ISSUE TITLE
`pdf2swf` issues with image conversion

### ISSUE THREAD

**Issue by ousia** [matthiaskramm/swftools#235]
Just in case @matthiaskramm would be interested in explaining this:

I have the following [sample presentation](https://github.com/matthiaskramm/swftools/files/15051304/sample-presentation.pdf).

It contains the following images (according to the relevant output from `mutool info`):

```
Images (9):
	5	(21 0 R):	[ JPX ] 2447x4064 8bpc DevRGB (15 0 R)
	5	(21 0 R):	[ JPX ] 816x1355 8bpc DevRGB (14 0 R)
	12	(41 0 R):	[ JPX ] 2447x4064 8bpc DevRGB (35 0 R)
	12	(41 0 R):	[ JPX ] 816x1355 8bpc DevRGB (37 0 R)
	28	(77 0 R):	[ JBIG2 ] 1711x2696 1bpc DevGray (72 0 R)
	38	(103 0 R):	[ JPX ] 2904x3892 8bpc DevRGB (97 0 R)
	38	(103 0 R):	[ JPX ] 968x1298 8bpc DevRGB (96 0 R)
	45	(122 0 R):	[ JPX ] 2904x3892 8bpc DevRGB (117 0 R)
	45	(122 0 R):	[ JPX ] 968x1298 8bpc DevRGB (116 0 R)
```

Converting it to SWF with plain `pdf2swf sample-presentation.pdf`, I get from `swfextract sample-presentation.swf`:

```
 [-j] 70 JPEGs: ID(s) 27, 29, 36, 38, 45, 47, 55, 57, 64, 66, 74, 76, 83, 85, 93, 95, 102, 104, 111, 113, 121, 123, 130, 132, 140, 142, 149, 151, 159, 161, 168, 170, 177, 179, 187, 189, 196, 198, 206, 208, 215, 217, 289, 291, 298, 300, 307, 309, 317, 319, 326, 328, 336, 338, 345, 347, 355, 357, 364, 366, 373, 375, 383, 385, 392, 394, 402, 404, 411, 413
 [-p] 7 PNGs: ID(s) 232, 238, 244, 251, 257, 264, 270
```

Is there any way to get `pdf2swf` converting images only once and keeping as many references as required?

This would both speed up conversion and dramatically reduce resulting SWF file size.

Many thanks for your help.

**Comment by ousia** [comment]
Even with a [simpler sample.pdf](https://github.com/matthiaskramm/swftools/files/15051377/simpler-sample.pdf) (which only embeds the image once), I get a size difference from about 500KB in the PDF source and 6.3MB in the SWF output.

`pdf2swf` gives a warning:

```
File contains pbm pictures
```

I have just uncompressed the PDF file and I get a similar size to the output SWF file.

Is there any way not to loose the image compression from the PDF file?

I mean, is there any way to get the same image file avoiding further quality degradation?

Just in case @matthiaskramm might be interested in explaining this.

Many thanks for your help.

**Comment by ROBERT-MCDOWELL** [comment]
to keep compression do
pdf2swf -j input.pdf -o output.swf
if it's jpeg
pdf2swf -j -s 85 input.pdf -o output.swf

**Comment by ousia** [comment]
> to keep compression

Many thanks for your fast reply, @ROBERT-MCDOWELL.

I’m afraid that it is impossible to keep image compression in my case.

I meant, transfering already compressed data from PDF to SWF, not to decompress data and compress them again.

The reason standing in the way seems to be the SWF format itself.

[It allows pure JPEG images](https://open-flash.github.io/mirrors/swf-spec-19.pdf#page=139), but neither JPEG2000, nor JBIG2 images.

So original compression is not allowed, so images have to be decompressed and compressed again (if I’m not missing anything). 

> ```
>  pdf2swf -j 85 input.pdf
>  ```

This seems to be how `pdf2swf` compresses JPEG images by default.

Many thanks for your help.

**Comment by ROBERT-MCDOWELL** [comment]
why not to optimize your pdf with all images in jpeg before to convert in swf?

**Comment by ousia** [comment]
Sorry for not replying before, @ROBERT-MCDOWELL.

This would be the only possibility to improve the conversion (just a little).

What took me by surprise is that `pdf2swf` didn’t keep indirect references and single image embedding.

**Comment by ousia** [comment]
Closing the issue myself, since it is not especially related to images.

The issue is to keep indirect references from PDF document and to avoid same object multiplication.
