### ISSUE TITLE
wav2swf wav_convert2mono() access except 

### ISSUE THREAD

**Issue by lcatro** [matthiaskramm/swftools#31]
Crash : [https://raw.githubusercontent.com/lcatro/My_PoC/master/swftools/wav2swf_wav_convert2mono_segment_fault](url)

Trigger : ./wav2swf swftools/wav2swf_wav_convert2mono_segment_fault 

Crash Detail :

fuzzer@ub16x64:~/fuzzing/swftools/src$ ./wav2swf swftools/wav2swf_wav_convert2mono_segment_fault 
ASAN:SIGSEGV
=================================================================
==19400==ERROR: AddressSanitizer: SEGV on unknown address 0x631000030000 (pc 0x000000438727 bp 0x7ffe0eb27030 sp 0x7ffe0eb26f30 T0)
    #0 0x438726 in wav_convert2mono (/home/fuzzer/fuzzing/swftools/src/wav2swf+0x438726)
    #1 0x40277a in main (/home/fuzzer/fuzzing/swftools/src/wav2swf+0x40277a)
    #2 0x7fccd015882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #3 0x401d78 in _start (/home/fuzzer/fuzzing/swftools/src/wav2swf+0x401d78)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 wav_convert2mono
==19400==ABORTING

**Comment by null1024-ws** [comment]
hi could you please provide the specific vulnerable line for this CVE? I'm preparing a benchmark for my directed fuzzer. Thanks!
